export { ReactComponent as Paimon48 } from './paimon/paimon48.svg'
export { ReactComponent as CalcSvg } from './calc/calculator.svg'
export { ReactComponent as CalcOutlineSvg } from './calc/calculatorOutline.svg'
export { ReactComponent as HomeSvg } from './home/home.svg'
export { ReactComponent as HistorySvg } from './history/history.svg'
export { ReactComponent as Hourglass } from './artifact/hourglass.svg'